name: "social-readme"
author: elvis
description: "Add social feed in your Readme"

inputs:
  gh_token:
    description: "GitHub access token with Repo scope"
    default: ${{ github.token }}
    required: true

#   repository:
#     description: "Your GitHub repository"
#     default: ${{ github.repository }}
#     required: false

#   commit_message:
#     description:  "commit message"
#     default: "Updated social rss by social-readme"
#     required: false

runs:
  using: "docker"
  image: "dockerfile"

branding:
  icon: "aperture"
  color: "green"

