name: "social-readme"
author: elvis
description: "Add social feed in your Readme"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
# inputs:
#   gh_token:
#     description: "GitHub access token with Repo scope"
#     default: ${{ github.token }}
#     required: true

#   repository:
#     description: "Your GitHub repository"
#     default: ${{ github.repository }}
#     required: false

#   commit_message:
#     description:  "commit message"
#     default: "Updated social rss by social-readme"
#     required: false

# runs:
#   using: "docker"
#   image: "Dockerfile"

# branding:
#   icon: "aperture"
#   color: "green"

