name: "social-readme"
author: elvis
description: "Add social feed in your Readme"
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
# inputs:
#   gh_token:
#     description: "GitHub access token with Repo scope"
#     default: ${{ github.token }}
#     required: true

#   repository:
#     description: "Your GitHub repository"
#     default: ${{ github.repository }}
#     required: false

#   commit_message:
#     description:  "commit message"
#     default: "Updated social rss by social-readme"
#     required: false

# runs:
#   using: "docker"
#   image: "Dockerfile"

# branding:
#   icon: "aperture"
#   color: "green"

